name: 'Publish Quartz GitHub Pages'
description: 'Publishes Quartz sites to GitHub Pages'
inputs:
  notes-dir:
    description: 'Path to the directory that contains the Markdown notes to be published.'
    required: false
    default: 'docs'
  quartz-config-dir:
    description: 'Path to the directory that contains files that should override the default setup/configuration of Quartz'
    required: false
    default: 'docs/.quartz-config'
  quartz-repo:
    description: 'Repository of Quartz fork that should be used'
    required: false
    default: 'jackyzha0/quartz'
  quartz-version:
    description: 'Version tag or commit hash of Quartz that should be used'
    required: false
    default: ''
  quartz-content-dir:
    description: 'Directory inside the Quartz directory, where the Markdown files need to be placed'
    required: false
    default: 'content'
  publishing-dir:
    description: 'Path inside the repository where Quartz is cloned to during the workflow (this directory should not be already be used)'
    required: false
    default: '.quartz-publish'
  node-version:
    description: 'Node.js version to use for the Quartz build'
    required: false
    default: '20'
runs:
  using: "composite"
  steps:
    - name: Checkout Quartz Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.quartz-repo }}
        ref: ${{ inputs.quartz-version }}
        path: ${{ inputs.publishing-dir }}
    
    - name: Apply Quartz Setup/Configuration
      run: |
        mkdir -p "${CONFIG_DIR}"
        rsync -a "${CONFIG_DIR}/" "${QUARTZ_DIR}/"
      shell: bash
      env:
        CONFIG_DIR: ${{ inputs.quartz-config-dir }}
        QUARTZ_DIR: ${{ inputs.publishing-dir }}

    - name: Copy Markdown notes for publishing
      run: |
        mkdir -p "${NOTES_DIR}"
        rsync -a "${NOTES_DIR}/" "${QUARTZ_DIR}/${CONTENT_DIR}/"
      shell: bash
      env:
        NOTES_DIR: ${{ inputs.notes-dir }}
        QUARTZ_DIR: ${{ inputs.publishing-dir }}
        CONTENT_DIR: ${{ inputs.quartz-content-dir }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Install Dependencies
      working-directory: ${{ inputs.publishing-dir }}
      run: npm ci
      shell: bash

    - name: Build Quartz Site
      working-directory: ${{ inputs.publishing-dir }}
      run: npx quartz build
      shell: bash
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.publishing-dir }}/public
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
